// Mock database with realistic data
export const mockUsers = [
  {
    id: "1",
    email: "admin@company.com",
    password: "password123",
    role: "admin",
    employee: {
      employeeId: "emp-1",
      firstName: "John",
      lastName: "Admin",
      employeeCode: "ADM001",
      department: { departmentId: "dept-1", departmentName: "Administration" },
      position: { positionId: "pos-1", positionName: "System Administrator" },
      phone: "+1234567890",
      hiredDate: "2020-01-15",
      salary: 75000,
    },
  },
  {
    id: "2",
    email: "employee@company.com",
    password: "password123",
    role: "employee",
    employee: {
      employeeId: "emp-2",
      firstName: "Jane",
      lastName: "Smith",
      employeeCode: "EMP001",
      department: { departmentId: "dept-2", departmentName: "Engineering" },
      position: { positionId: "pos-2", positionName: "Software Developer" },
      phone: "+1234567891",
      hiredDate: "2021-03-10",
      salary: 85000,
    },
  },
]

export const mockEmployees = [
  {
    employeeId: "emp-1",
    employeeCode: "ADM001",
    firstName: "John",
    lastName: "Admin",
    email: "admin@company.com",
    phone: "+1234567890",
    department: { departmentId: "dept-1", departmentName: "Administration" },
    position: { positionId: "pos-1", positionName: "System Administrator" },
    hiredDate: "2020-01-15",
    salary: 75000,
    status: "active",
  },
  {
    employeeId: "emp-2",
    employeeCode: "EMP001",
    firstName: "Jane",
    lastName: "Smith",
    email: "employee@company.com",
    phone: "+1234567891",
    department: { departmentId: "dept-2", departmentName: "Engineering" },
    position: { positionId: "pos-2", positionName: "Software Developer" },
    hiredDate: "2021-03-10",
    salary: 85000,
    status: "active",
  },
  {
    employeeId: "emp-3",
    employeeCode: "EMP002",
    firstName: "Mike",
    lastName: "Johnson",
    email: "mike@company.com",
    phone: "+1234567892",
    department: { departmentId: "dept-3", departmentName: "Marketing" },
    position: { positionId: "pos-3", positionName: "Marketing Manager" },
    hiredDate: "2021-06-20",
    salary: 70000,
    status: "active",
  },
  {
    employeeId: "emp-4",
    employeeCode: "EMP003",
    firstName: "Sarah",
    lastName: "Wilson",
    email: "sarah@company.com",
    phone: "+1234567893",
    department: { departmentId: "dept-4", departmentName: "HR" },
    position: { positionId: "pos-4", positionName: "HR Specialist" },
    hiredDate: "2022-01-05",
    salary: 65000,
    status: "active",
  },
  {
    employeeId: "emp-5",
    employeeCode: "EMP004",
    firstName: "David",
    lastName: "Brown",
    email: "david@company.com",
    phone: "+1234567894",
    department: { departmentId: "dept-2", departmentName: "Engineering" },
    position: { positionId: "pos-5", positionName: "Senior Developer" },
    hiredDate: "2019-08-12",
    salary: 95000,
    status: "active",
  },
]

export const mockEvents = [
  {
    eventId: "evt-1",
    eventName: "Daily Work Session",
    memo: "Regular daily work attendance",
    startDate: new Date("2024-01-15T08:00:00"),
    endDate: new Date("2024-01-15T18:00:00"),
    status: "active",
    createdAt: new Date("2024-01-10"),
  },
  {
    eventId: "evt-2",
    eventName: "Team Meeting",
    memo: "Weekly team sync meeting",
    startDate: new Date("2024-01-15T10:00:00"),
    endDate: new Date("2024-01-15T11:00:00"),
    status: "active",
    createdAt: new Date("2024-01-12"),
  },
  {
    eventId: "evt-3",
    eventName: "Training Session",
    memo: "Monthly training and development",
    startDate: new Date("2024-01-20T09:00:00"),
    endDate: new Date("2024-01-20T17:00:00"),
    status: "active",
    createdAt: new Date("2024-01-08"),
  },
]

export const mockAttendances = [
  {
    attendanceId: "att-1",
    employeeId: "emp-1",
    eventId: "evt-1",
    checkIn: new Date("2024-01-15T09:00:00"),
    checkOut: new Date("2024-01-15T17:30:00"),
    method: "phone",
    status: "active",
    note: "Regular check-in",
    employee: mockEmployees[0],
    event: mockEvents[0],
  },
  {
    attendanceId: "att-2",
    employeeId: "emp-2",
    eventId: "evt-1",
    checkIn: new Date("2024-01-15T09:15:00"),
    checkOut: null,
    method: "phone",
    status: "active",
    note: "Late arrival",
    employee: mockEmployees[1],
    event: mockEvents[0],
  },
  {
    attendanceId: "att-3",
    employeeId: "emp-3",
    eventId: "evt-2",
    checkIn: new Date("2024-01-15T10:00:00"),
    checkOut: new Date("2024-01-15T11:00:00"),
    method: "biometric",
    status: "active",
    note: "Meeting attendance",
    employee: mockEmployees[2],
    event: mockEvents[1],
  },
]

export const mockLeaveRequests = [
  {
    leaveId: "leave-1",
    employeeId: "emp-2",
    leaveType: "annual",
    startDate: new Date("2024-01-20"),
    endDate: new Date("2024-01-22"),
    reason: "Family vacation",
    status: "pending",
    createdAt: new Date("2024-01-10"),
    employee: mockEmployees[1],
  },
  {
    leaveId: "leave-2",
    employeeId: "emp-3",
    leaveType: "sick",
    startDate: new Date("2024-01-18"),
    endDate: new Date("2024-01-18"),
    reason: "Medical appointment",
    status: "approved",
    approvedAt: new Date("2024-01-12"),
    createdAt: new Date("2024-01-11"),
    employee: mockEmployees[2],
  },
]

export const mockNotifications = [
  {
    id: "notif-1",
    type: "attendance",
    title: "New Check-in",
    message: "Jane Smith checked in for Daily Work Session",
    timestamp: new Date(),
    read: false,
  },
  {
    id: "notif-2",
    type: "leave_request",
    title: "Leave Request",
    message: "Jane Smith requested annual leave for Jan 20-22",
    timestamp: new Date(Date.now() - 30 * 60 * 1000),
    read: false,
  },
  {
    id: "notif-3",
    type: "attendance",
    title: "Late Check-in",
    message: "Mike Johnson checked in 15 minutes late",
    timestamp: new Date(Date.now() - 60 * 60 * 1000),
    read: true,
  },
]

// In-memory storage for runtime data
export const runtimeData = {
  attendances: [...mockAttendances],
  events: [...mockEvents],
  employees: [...mockEmployees],
  leaveRequests: [...mockLeaveRequests],
  notifications: [...mockNotifications],
  qrCodes: [] as any[],
}
